/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialIndexRouteImport } from './routes/social/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as SocialTermsRouteImport } from './routes/social/terms'
import { Route as SocialPrivacyRouteImport } from './routes/social/privacy'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialIndexRoute = SocialIndexRouteImport.update({
  id: '/social/',
  path: '/social/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialTermsRoute = SocialTermsRouteImport.update({
  id: '/social/terms',
  path: '/social/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialPrivacyRoute = SocialPrivacyRouteImport.update({
  id: '/social/privacy',
  path: '/social/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/social/privacy': typeof SocialPrivacyRoute
  '/social/terms': typeof SocialTermsRoute
  '/articles/': typeof ArticlesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/social/': typeof SocialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/social/privacy': typeof SocialPrivacyRoute
  '/social/terms': typeof SocialTermsRoute
  '/articles': typeof ArticlesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/social': typeof SocialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/social/privacy': typeof SocialPrivacyRoute
  '/social/terms': typeof SocialTermsRoute
  '/articles/': typeof ArticlesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/social/': typeof SocialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles/$slug'
    | '/social/privacy'
    | '/social/terms'
    | '/articles/'
    | '/projects/'
    | '/social/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles/$slug'
    | '/social/privacy'
    | '/social/terms'
    | '/articles'
    | '/projects'
    | '/social'
  id:
    | '__root__'
    | '/'
    | '/articles/$slug'
    | '/social/privacy'
    | '/social/terms'
    | '/articles/'
    | '/projects/'
    | '/social/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  SocialPrivacyRoute: typeof SocialPrivacyRoute
  SocialTermsRoute: typeof SocialTermsRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SocialIndexRoute: typeof SocialIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/': {
      id: '/social/'
      path: '/social'
      fullPath: '/social/'
      preLoaderRoute: typeof SocialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/terms': {
      id: '/social/terms'
      path: '/social/terms'
      fullPath: '/social/terms'
      preLoaderRoute: typeof SocialTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/privacy': {
      id: '/social/privacy'
      path: '/social/privacy'
      fullPath: '/social/privacy'
      preLoaderRoute: typeof SocialPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  SocialPrivacyRoute: SocialPrivacyRoute,
  SocialTermsRoute: SocialTermsRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SocialIndexRoute: SocialIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
